
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join('..', 'pyol', 'tools')))
import OLBaseConfig

OLBaseConfig.prefix = '..'
config = OLBaseConfig.get_config(ARGLIST)

if config['import_path']:
    env_path = os.environ.get('PATH', '')
    env_ld_library_path = os.environ.get('LD_LIBRARY_PATH', '')
else:
    env_path = []
    env_ld_library_path = []

env = Environment(tools = ['default', config['fortran_compiler']],
                  ENV = {"PATH": env_path, "LD_LIBRARY_PATH": env_ld_library_path},
                  F90FLAGS = config['f90_flags'] + config['generic_optimisation'],
                  F90PATH = [os.path.join('..', 'lib_src', 'openloops', 'mod')],
                  LIBPATH = [os.path.join('..', config['generic_lib_dir'])],
                  RPATH = [os.path.join('..', config['generic_lib_dir'])])

env.Program('OL_minimal.f90', LIBS = ['openloops'])
env.Program('OL_fortran.f90', LIBS = ['openloops'])
env.Program('OL_cpp.cpp', LIBS = ['openloops'])
env.Program('OL_blha.cpp', LIBS = ['openloops'])
